### ISSUE TITLE
Doesn't support local dependencies

### ISSUE THREAD

**Issue by DivyanshuBhoyar** [vchrombie/peodd#10]
![image](https://github.com/vchrombie/peodd/assets/64900631/15f71c6c-374b-4882-b4c1-9669bac26ac6)

##### Pyproject.toml file:
```toml
[tool.poetry.dev-dependencies]
pylint = ">=2.6.0,<2.14"
mypy = ">=0.782"
pytest = ">=6.0.2"
pytest-cov = ">=2.10.1"
pre-commit = ">=2.7.1"
black = ">=22.3.0"
taskipy = ">=1.3.0"
isort = ">=5.5.4"
locust = "^1.0.2"
znlp-translate = { path = "../znlp_translate", develop = true }
znlp-language-detection = { path = "../znlp_language_detection", develop = true }
znlp-api = { path = "../znlp_api", develop = true }
```

Is there a way to export local dependencies ?
