### ISSUE TITLE
peodd fails to extract "extras"

### ISSUE THREAD

**Issue by thiras** [vchrombie/peodd#3]
peodd has failed at my dev dependencies.

```toml
[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
bandit = "^1.7.0"
black = "^21.6b0"
flake8 = "^3.9.2"
flake8-black = "^0.2.1"
pre-commit = "^2.13.0"
isort = "^5.9.1"
flake8-django = "^1.1.2"
coverage = { extras = ["toml"], version = "^5.5" }
jupyterlab = "^3.0.16"
types-requests = "^2.25.0"
django-stubs = "^1.9.0"
```

The `coverage` is missing in the requirements-dev.txt from `poedd -o requirements-dev.txt`
